
/*
 * Editor client script for DB table report
 * Automatically generated by http://editor.datatables.net/generator
 */
  
(function($){

$(document).ready(function() {
	var reportTable;
	var theReport = 0;
	var theTemplateCollection;
	var theTemplateName;
	var theTemplateColumn;
	
	var editor = new $.fn.dataTable.Editor( {
		"ajax": "php/table.report.php",
		"table": "#report",
		"fields": [
			{
				"label": "Name",
				"name": "report.name",
				"type": "text",
			},
			{
				"label": "Template",
				"name": "report.idtemplate",
				"type": "select"
			},
			{
				"label": "Output Dir",
				"name": "report.outputRoot",
				"type": "text"
			}
		]
	} );

	$('#report').dataTable( {
		"dom": "Tfrtip",
		"ajax": "php/table.report.php",
		"columns": [
			{"data": "report.name"},
			{"data": "templateFull.fullName"},
			{"data": "report.outputRoot"},
		],
		"tableTools": {
			"sRowSelect": "os",
			"fnRowSelected": function ( nodes ) {setReport(reportTable, nodes);},			
			"aButtons": [
				{ "sExtends": "editor_create", "editor": editor },
				{ "sExtends": "editor_edit",   "editor": editor },
				{ "sExtends": "editor_remove", "editor": editor },
				{ "sExtends": "text", "sButtonText": "Generate", 
					"fnClick": function ( nButton, oConfig, oFlash ) {generateReport();} 
                }  				
			]
		}
	} );
	reportTable =  $('#report').DataTable();
	
	function setReport(table, nodes) {
		theReport = table.row(nodes).data().report.idreport;
		theTemplateCollection = table.row(nodes).data().templateFull.collectionName;
		theTemplateName = table.row(nodes).data().templateFull.name;
		theTemplateColumn = table.row(nodes).data().templateFull.columnValue;		
		var theName = table.row(nodes).data().report.name;
		var event = new CustomEvent('reportSet');
		$( ".listener" ).trigger( "reportSet", [theName, theReport]  );
	}
	
	function generateReport() {
		if (theReport == 0) {
			alert( 'Please select a report' );
		} else {
			var parameters = "";
			parameters += "collection=" + theTemplateCollection.trim();
			parameters += "&name=" + theTemplateName.trim();
			if ( theTemplateColumn != "" ) {
				parameters += "&column=" + theTemplateColumn.trim();
			} 
			
			var replaceTable = $('#reportReplace').DataTable();
			var replaceData =  replaceTable.rows().data();
			for (row = 0 ; row < replaceData.length ; row++) {
				var rowData = replaceTable.row(row).data();
				parameters += "&" + rowData.reportReplace.fromValue + "=" + rowData.reportReplace.toValue;
			}
			win=window.open("http://localhost:8080/MergeTool/Merge.html?" + parameters, '_blank');
			win.focus();
		}
	}

} );

}(jQuery));

