/* ----------------------------------------------------- */
/* Table IDMU_TEMPLATE                                   */
/* ----------------------------------------------------- */
CREATE TABLE IDMU_TEMPLATE (
  COLLECTION VARCHAR2(45) NOT NULL,
  TEMPLATE_NAME VARCHAR2(45) DEFAULT '' NOT NULL,
  COLUMN_VALUE VARCHAR2(45) DEFAULT '' NOT NULL,
  OUTPUT_FILE VARCHAR2(45) DEFAULT '' NULL,
  DESCRIPTION VARCHAR2(45) DEFAULT '' NULL,
  CONTENT VARCHAR2(4000) DEFAULT '' NULL,
PRIMARY KEY (COLLECTION, TEMPLATE_NAME, COLUMN_VALUE),
CONSTRAINT IDMU_TEMPLATE_uniq UNIQUE (COLLECTION, TEMPLATE_NAME, COLUMN_VALUE));

/
/* ----------------------------------------------------- */
/* Table IDMU_DIRECTIVE                                  */
/* ----------------------------------------------------- */
CREATE TABLE IDMU_DIRECTIVE (
  COLLECTION VARCHAR2(45) NOT NULL,
  TEMPLATE_NAME VARCHAR2(45) DEFAULT '' NOT NULL,
  COLUMN_VALUE VARCHAR2(45) DEFAULT '' NOT NULL,
  SEQUENCE NUMBER(10) NOT NULL,
  DIR_TYPE NUMBER(10) NOT NULL,
  DESCRIPTION VARCHAR2(45) DEFAULT '' NULL,
  SOFT_FAIL CHAR(1) DEFAULT 'N' NOT NULL,
  DIR_1 VARCHAR2(1024) DEFAULT NULL NULL,
  DIR_2 VARCHAR2(1024) DEFAULT NULL NULL,
  DIR_3 VARCHAR2(1024) DEFAULT NULL NULL,
  DIR_4 VARCHAR2(1024) DEFAULT NULL NULL,
  PRO_1 VARCHAR2(1024) DEFAULT NULL NULL,
  PRO_2 VARCHAR2(1024) DEFAULT NULL NULL,
  PRO_3 VARCHAR2(1024) DEFAULT NULL NULL,
  PRO_4 VARCHAR2(4000) DEFAULT NULL NULL,
PRIMARY KEY (COLLECTION, TEMPLATE_NAME, COLUMN_VALUE, SEQUENCE)
,
CONSTRAINT fk_sqlDirective_template1
    FOREIGN KEY (COLLECTION, TEMPLATE_NAME, COLUMN_VALUE)
    REFERENCES IDMU_TEMPLATE (COLLECTION, TEMPLATE_NAME, COLUMN_VALUE)
    ON DELETE CASCADE);

CREATE INDEX fk_sqlDirective_template1 ON IDMU_DIRECTIVE (COLLECTION ASC, TEMPLATE_NAME ASC, COLUMN_VALUE ASC);
INSERT INTO IDMU_TEMPLATE (COLLECTION, TEMPLATE_NAME, COLUMN_VALUE, CONTENT) values ("system", "test", "", "This is the default template");
