-- -----------------------------------------------------
-- Table `IDMU`.`DIRECTIVE_TYPE`
-- -----------------------------------------------------
CREATE TABLE `IDMU`.`DIRECTIVE_TYPE` (
  `TYPE` INT(11) NOT NULL AUTO_INCREMENT,
  `MEANING` VARCHAR(45) NULL DEFAULT '',
PRIMARY KEY (`TYPE`));


-- -----------------------------------------------------
-- Table `IDMU`.`TEMPLATE`
-- -----------------------------------------------------
CREATE TABLE `IDMU`.`TEMPLATE` (
  `ID_TEMPLATE` INT(11) NOT NULL AUTO_INCREMENT,
  `COLLECTION` VARCHAR(45) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL DEFAULT '',
  `COLUMN_VALUE` VARCHAR(45) NOT NULL DEFAULT '',
  `OUTPUT` VARCHAR(45) NULL DEFAULT '',
  `DESCRIPTION` VARCHAR(45) NULL DEFAULT '',
  `CONTENT` VARCHAR(4096) NULL DEFAULT '',
PRIMARY KEY (`ID_TEMPLATE`),
UNIQUE INDEX `UNIQUE` (`COLLECTION` ASC, `NAME` ASC, `COLUMN_VALUE` ASC));

-- -----------------------------------------------------
-- Table `IDMU`.`DIRECTIVE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IDMU`.`DIRECTIVE` (
  `ID_TEMPLATE` INT(11) NOT NULL,
  `SEQUENCE` INT(11) NOT NULL,
  `TYPE` INT(11) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NULL DEFAULT '',
  `SOFT_FAIL` CHAR(1) NOT NULL DEFAULT 'N',
  `DIR_1` VARCHAR(1024) NULL DEFAULT NULL,
  `DIR_2` VARCHAR(1024) NULL DEFAULT NULL,
  `DIR_3` VARCHAR(1024) NULL DEFAULT NULL,
  `DIR_4` VARCHAR(1024) NULL DEFAULT NULL,
  `PRO_1` VARCHAR(1024) NULL DEFAULT NULL,
  `PRO_2` VARCHAR(1024) NULL DEFAULT NULL,
  `PRO_3` VARCHAR(1024) NULL DEFAULT NULL,
  `PRO_4` VARCHAR(4096) NULL DEFAULT NULL,
PRIMARY KEY (`ID_TEMPLATE`, `SEQUENCE`),
INDEX `fk_directive_codeDirective1_idx` (`TYPE` ASC),
INDEX `fk_sqlDirective_template1` (`ID_TEMPLATE` ASC),
CONSTRAINT `fk_directive_codeDirective1`
    FOREIGN KEY (`TYPE`)
    REFERENCES `IDMU`.`DIRECTIVE_TYPE` (`TYPE`)
    ON UPDATE CASCADE,
CONSTRAINT `fk_sqlDirective_template1`
    FOREIGN KEY (`ID_TEMPLATE`)
    REFERENCES `IDMU`.`TEMPLATE` (`ID_TEMPLATE`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
