
CREATE TABLE IDMU_TEMPLATE (
  COLLECTION 	VARCHAR(100) NOT NULL,
  TEMPLATE_NAME VARCHAR(100) NOT NULL DEFAULT '',
  COLUMN_VALUE 	VARCHAR(100) NOT NULL DEFAULT '',
  OUTPUT_FILE 	VARCHAR(250) NULL DEFAULT '',
  DESCRIPTION 	VARCHAR(250) NULL DEFAULT '',
  CONTENT 		VARCHAR(4000) NULL DEFAULT '',
  PRIMARY KEY (COLLECTION, TEMPLATE_NAME, COLUMN_VALUE)
 );
  
CREATE TABLE IDMU_DIRECTIVE (
  COLLECTION 	VARCHAR(100) NOT NULL,
  TEMPLATE_NAME VARCHAR(100) NOT NULL DEFAULT '',
  COLUMN_VALUE 	VARCHAR(100) NOT NULL DEFAULT '',
  SEQUENCE		INT NOT NULL DEFAULT 0,
  DIR_TYPE 		INT,
  DESCRIPTION 	VARCHAR(250) NULL DEFAULT '',
  SOFT_FAIL 	CHAR(1) NOT NULL DEFAULT 'N',
  DIR_1 		VARCHAR(1024) NULL DEFAULT NULL,
  DIR_2 		VARCHAR(1024) NULL DEFAULT NULL,
  DIR_3 		VARCHAR(1024) NULL DEFAULT NULL,
  DIR_4 		VARCHAR(1024) NULL DEFAULT NULL,
  PRO_1 		VARCHAR(1024) NULL DEFAULT NULL,
  PRO_2 		VARCHAR(1024) NULL DEFAULT NULL,
  PRO_3 		VARCHAR(1024) NULL DEFAULT NULL,
  PRO_4 		VARCHAR(4000) NULL DEFAULT NULL,
  PRIMARY KEY (COLLECTION, TEMPLATE_NAME, COLUMN_VALUE, SEQUENCE),
  CONSTRAINT fk_DIRECTIVE_TEMPLATE
    FOREIGN KEY (COLLECTION , TEMPLATE_NAME , COLUMN_VALUE)
    REFERENCES IDMU_TEMPLATE (COLLECTION , TEMPLATE_NAME , COLUMN_VALUE)
    ON DELETE CASCADE
);

INSERT INTO IDMU_TEMPLATE (COLLECTION, TEMPLATE_NAME, COLUMN_VALUE, CONTENT) values ('system', 'default', '<null>', 'This is the Default Template');
