INSERT INTO `dragonfly`.`collection` (`idcollection`,`name`,`tableName`,`columnName`,`sampleValue`) VALUES (7,'test.root','','','');
INSERT INTO `dragonfly`.`collection` (`idcollection`,`name`,`tableName`,`columnName`,`sampleValue`) VALUES (8,'test.contact','contact','preference','');

INSERT INTO `dragonfly`.`template` (`idtemplate`,`idcollection`,`columnValue`,`name`,`type`,`output`,`description`,`content`) VALUES (34,7,'','RPTroot',1,'','All Customers Report (with Bulk Mail files)','<html>\n<head></head>\n<body>\n<h1> All Customers Report </h1>\n<table border=\"1\" class=\"display\" id=\"customer\" >\n	<thead>\n		<tr>\n			<th>Name</th>\n			<th>Revenue</th>\n			<th>Profit</th>\n			<th>Primary Contact</th>\n			<th>City</th>\n			<th>State</th>\n			<th>Phone</th>\n		</tr>\n	</thead>\n	<tbody>\n<tkBookmark name=\"customer\"/>\n	</tbody>\n</table>\n</body>\n</html>');
INSERT INTO `dragonfly`.`template` (`idtemplate`,`idcollection`,`columnValue`,`name`,`type`,`output`,`description`,`content`) VALUES (35,7,'','customer',1,'','Customer level Report','		<tr>\n			<td><h1>{name}</h1></td>\n			<td><h2>{revenue}</h2></td>\n			<td><h2>{profit}</h2></td>\n			<td><h2>{primary}</h2></td>\n			<td><h2>{city}</h2></td>\n			<td><h2>{state}</h2></td>\n			<td><h2>{phone}</h2></td>\n		</tr>\n		<tr>\n			<th></th>\n			<th></th>\n			<th>Contacts</th>\n			<th>Name</th>\n			<th>Preference</th>\n			<th>eMail</th>\n			<th>Phone</th>\n		</tr>\n<tkBookmark name=\"contact\"/>\n<tkBookmark name=\"notification\"/>\n');
INSERT INTO `dragonfly`.`template` (`idtemplate`,`idcollection`,`columnValue`,`name`,`type`,`output`,`description`,`content`) VALUES (36,8,'','contact',1,'','Contact Report','				<tr>\n					<td></td>\n					<td></td>\n					<td></td>\n					<td>{name}</td>\n					<td>{preference}</td>\n					<td>{email}</td>\n					<td>{phone}</td>\n				</tr>\n');
INSERT INTO `dragonfly`.`template` (`idtemplate`,`idcollection`,`columnValue`,`name`,`type`,`output`,`description`,`content`) VALUES (38,7,'','contacteMail',1,'email/{name}.email.txt','Sendmail HTML File','From: \"Renewals\" <renew@{corpUrl}>\nTo: \"{name}\" <{email}>\nSubject: Subscription Renewal\nMIME-Version: 1.0\nContent-Type: text/html; charset=iso-8859-1\nContent-Disposition: inline\n\n<html>\n    <body>\n        Please visit http://{corpUrl}/renew?name=\"{name}\" to renew your subscription to our valuable monthly news letter.\n    </body>\n</html>\n');
INSERT INTO `dragonfly`.`template` (`idtemplate`,`idcollection`,`columnValue`,`name`,`type`,`output`,`description`,`content`) VALUES (39,7,'','contactSMS',1,'','Send SMS Command to a contact','curl http://textbelt.com/text -d number={phone} -d \"message=Please visit http://{corpUrl}/renew?name={name} to renew your subscription\";\n');
INSERT INTO `dragonfly`.`template` (`idtemplate`,`idcollection`,`columnValue`,`name`,`type`,`output`,`description`,`content`) VALUES (40,8,'paper','notification',1,'bulkMail/{name}.mailfile.txt','Bulk Mail Document','##ENVELOPE\nSpacely Sprockets\n{corpStreet}\n{corpCity}, {corpState} {corpZip}\n									To {name}\n									To {street}\n									To {city}, {state}, {zip}\n##MESSAGE\nDear {name};\n\nIt is that time of year again, please visit http://{corpUrl}/renew?name={name} to renew your subscription to our valuable monthly newsletter.\n\nSincerely\n\nThe Spacely Sprockets team!\n\n##END\n\n{tkReplaceValues}');
INSERT INTO `dragonfly`.`template` (`idtemplate`,`idcollection`,`columnValue`,`name`,`type`,`output`,`description`,`content`) VALUES (41,7,'','allReports',1,'','Generate SMS, eMail, Bulk Mail and Reports','<tkBookmark name=\"RPTroot\"/>\n<tkBookmark name=\"SMSroot\"/>\n<tkBookmark name=\"SMTProot\"/>');
INSERT INTO `dragonfly`.`template` (`idtemplate`,`idcollection`,`columnValue`,`name`,`type`,`output`,`description`,`content`) VALUES (43,7,'','SMSroot',1,'sendAllSms.sh','Send SMS Script','<tkBookmark name=\"contactSMS\"/>\n');
INSERT INTO `dragonfly`.`template` (`idtemplate`,`idcollection`,`columnValue`,`name`,`type`,`output`,`description`,`content`) VALUES (45,7,'','SMTProot',1,'sendAllEmails.sh','Sendmail Script','<tkBookmark name=\"contactSMTP\"/>\n');
INSERT INTO `dragonfly`.`template` (`idtemplate`,`idcollection`,`columnValue`,`name`,`type`,`output`,`description`,`content`) VALUES (46,7,'','contactSMTP',1,'','Insert script line, generate output file','cat ./email/{name}.email.txt | sendmail -i -t\n<tkBookmark name=\"contacteMail\"/>');
INSERT INTO `dragonfly`.`template` (`idtemplate`,`idcollection`,`columnValue`,`name`,`type`,`output`,`description`,`content`) VALUES (47,8,'','notification',1,'','Empty Template','');
