<?php if (!defined('DATATABLES')) exit(); // Ensure being used in DataTables env.

/*
 * DB connection script for Editor
 * Automatically generated by http://editor.datatables.net/generator
 */

// Enable error reporting for debugging (remove for production)
error_reporting(E_ALL);
ini_set('display_errors', '1');

/*
 * Edit the following with your database connection options
 */
$sql_details = array(
	"type" => "Mysql",
	"user" => getenv('OPENSHIFT_MYSQL_DB_USERNAME'),
	"pass" => getenv('OPENSHIFT_MYSQL_DB_PASSWORD'),
	"host" => getenv('OPENSHIFT_MYSQL_DB_HOST'),
	"port" => getenv('OPENSHIFT_MYSQL_DB_PORT'),
	"db"   => "MergeTool"
);

    //    ('DB_HOST', getenv('OPENSHIFT_MYSQL_DB_HOST')
    //    ('DB_PORT', getenv('OPENSHIFT_MYSQL_DB_PORT')
    //    ('DB_USER', getenv('OPENSHIFT_MYSQL_DB_USERNAME')
    //    ('DB_PASS', getenv('OPENSHIFT_MYSQL_DB_PASSWORD')
    //    ('DB_NAME', getenv('OPENSHIFT_APP_NAME')
