<?php

/*
 * Editor server script for DB table directive
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "../../../Editor/php/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'directive', 'iddirective' )
	->fields(
		Field::inst( 'directive.iddirective' ),
		Field::inst( 'directive.idtemplate' ),
		Field::inst( 'directive.idcollection' )->options( 'collection', 'idcollection', 'name' ),
		Field::inst( 'directive.type' )->options( 'codesDtype', 'code', 'meaning' ),
		Field::inst( 'directive.description' ),
		Field::inst( 'directive.selectColumns' ),
		Field::inst( 'directive.fromTables' ),
		Field::inst( 'directive.whereCondition' ),
		Field::inst( 'directive.fromValue' ),
		Field::inst( 'directive.toValue' ),
		Field::inst( 'directive.notLast' ),
		Field::inst( 'directive.onlyLast' ),
		Field::inst( 'collection.name' ),
		Field::inst( 'codesDtype.meaning' )
	)
	->where( 'directive.idtemplate', $_POST['templateId'] )
	->leftJoin( 'collection', 'collection.idcollection', '=', 'directive.idcollection' )
	->leftJoin( 'codesDtype', 'codesDtype.code', '=', 'directive.type' )
	->process( $_POST )
	->json();

