<?php

/*
 * Editor server script for DB table report
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "../../../Editor/php/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'report', 'idreport' )
	->fields(
		Field::inst( 'report.idreport' ),
		Field::inst( 'report.idtemplate' )->options( 'templateFull', 'idtemplate', 'fullName' ),
		Field::inst( 'report.name' ),
		Field::inst( 'report.outputRoot' ),
		Field::inst( 'templateFull.fullName' ),
		Field::inst( 'templateFull.collectionName' ),
		Field::inst( 'templateFull.name' ),
		Field::inst( 'templateFull.columnValue' )
	)
	->leftJoin( 'templateFull', 'templateFull.idtemplate', '=', 'report.idtemplate' )
	->process( $_POST )
	->json();
