<?php

/*
 * Editor server script for DB table template
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'template', 'idtemplate' )
	->fields(
		Field::inst( 'template.idtemplate' ),
		Field::inst( 'template.idcollection' )->options( 'collection', 'idcollection', 'name' ),
		Field::inst( 'template.columnValue' ),
		Field::inst( 'template.name' ),
		Field::inst( 'template.type' )->options( 'codesTtype', 'code', 'meaning' ),
		Field::inst( 'template.output' ),
		Field::inst( 'template.description' ),
		Field::inst( 'template.content' ),
		Field::inst( 'collection.name' ),
		Field::inst( 'codesTtype.meaning' )
	)
	->leftJoin( 'collection', 'collection.idcollection', '=', 'template.idcollection' )
	->leftJoin( 'codesTtype', 'codesTtype.code', '=', 'template.type' )
	->process( $_POST )
	->json();
